docs: add Integration Test in MSA
jhhong0509/study-architecture pull request #10
Opened 2022-04-04 09:10 UTC by jhhong0509

don't use end-to-end test in most cases

2022-04-09 13:46 UTC, leeseojune53 commented
내일 볼게여.. ㅎㅎ

2022-04-10 09:56 UTC, leeseojune53 requested changes

2022-04-10 09:56 UTC, leeseojune53 commented on msa/book/10 마이크로서비스 테스트-2/01. 통합 테스트 작성하기.md
> +다음 그림은 Spring Cloud Context를 사용해 Rest기반 Communication Test를 하는 과정이다.
`Spring Cloud Contract` 인 것 같아요

2022-04-10 12:31 UTC, jhhong0509 commented on msa/book/10 마이크로서비스 테스트-2/01. 통합 테스트 작성하기.md
> +다음 그림은 Spring Cloud Context를 사용해 Rest기반 Communication Test를 하는 과정이다.
헉 오타네요 고치겠습니다

2022-04-13 11:04 UTC, leeseojune53 approved these changes

2022-04-13 11:05 UTC, merged